language: bash
dist: trusty
sudo: required
env: VERSION=v0.4.5
script: make build
addons:
  artifacts:
    paths:
    - shellcheck-${VERSION}.tar.bz2
    - shellcheck-${VERSION}.tar.bz2.sha256sum
    target_paths:
    - /binaries/ubuntu/14.04/x86_64
