#!/usr/bin/env bash

set -o errexit

main() {
  local shellcheck_clone="${1}"
  local version="${2}"
  local basedir="${PWD}"

  docker build -t shellcheck .
  echo "Exporting artifacts to ${basedir}"
  docker run --rm -it -v "${basedir}:/mnt" shellcheck \
    cp -v /root/.cabal/bin/shellcheck /mnt/shellcheck

  mkdir -p "build/shellcheck-${version}"
  cp -v "${basedir}/shellcheck" "build/shellcheck-${version}/shellcheck"

  pushd "build/shellcheck-${version}"
  sha256sum shellcheck >SHA256SUMS
  popd &>/dev/null

  pushd build
  tar -cjvf "shellcheck-${version}.tar.bz2" "shellcheck-${version}"
  stat "shellcheck-${version}.tar.bz2"
}

main "$@"
